services:
  shiori:
    image: ghcr.io/flurbudurbur/shiori:develop
    container_name: shiori
    volumes:
      - ./config:/config
    ports:
      - '127.0.0.1:8282:8282'
    depends_on:
      - valkey
      - postgres
  postgres:
    container_name: shiori-postgres
    image: postgres:17.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=shiori
      - POSTGRES_PASSWORD=shiori
    volumes:
      - postgres:/var/lib/postgresql/data
  valkey:
    container_name: shiori-valkey
    image: valkey/valkey:latest
    restart: always
    volumes:
      - valkey-data:/data
    command: [ "valkey-server", "--requirepass", "shiori" ]
volumes:
  postgres:
    driver: local
  valkey-data:
    driver: local
